-- Nach dem Ausführen von schema.sql: Rezepte einfügen (einmal ausführen).
-- Die Werte entsprechen den Standard-Rezepten der App.

insert into public.recipes (id, title, description, category, prep_time_minutes, cook_time_minutes, servings, ingredients, steps, image)
values
  ('1', 'Spaghetti Carbonara', 'Klassische italienische Pasta mit cremiger Ei-Käse-Sauce und knusprigem Speck.', 'Hauptgericht', 15, 20, 4, '["400 g Spaghetti","200 g Guanciale oder Pancetta","4 Eigelb + 2 ganze Eier","100 g Pecorino Romano, gerieben","Schwarzer Pfeffer","Salz für das Nudelwasser"]'::jsonb, '["Nudelwasser mit Salz aufkochen, Spaghetti al dente kochen.","Guanciale in Streifen schneiden und in einer Pfanne ohne Fett knusprig anbraten.","Eier mit Pecorino und viel Pfeffer verquirlen.","Nudeln abgießen, etwas Nudelwasser aufheben. Nudeln in die Pfanne zum Speck geben, vom Herd nehmen.","Ei-Mix unterrühren, bei Bedarf mit Nudelwasser verdünnen. Sofort servieren."]'::jsonb, 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80'),
  ('2', 'Kürbissuppe mit Ingwer', 'Cremige Suppe mit Hokkaido-Kürbis und frischem Ingwer – perfekt für den Herbst.', 'Suppe', 20, 25, 4, '["1 Hokkaido-Kürbis (ca. 800 g)","1 Zwiebel","2 cm frischer Ingwer","500 ml Gemüsebrühe","200 ml Sahne","Olivenöl, Salz, Pfeffer, Muskat","Kürbiskerne und Kräuter zum Garnieren"]'::jsonb, '["Kürbis waschen, entkernen und in Würfel schneiden (mit Schale).","Zwiebel und Ingwer fein hacken, in Öl andünsten.","Kürbis zugeben, mit Brühe ablöschen und 20 Min. weich kochen.","Pürieren, Sahne einrühren, mit Salz, Pfeffer und Muskat abschmecken.","Mit Kürbiskernen und Kräutern servieren."]'::jsonb, null),
  ('3', 'Caesar Salad', 'Römischer Salat mit knusprigen Croutons, Parmesan und cremigem Dressing.', 'Salat', 25, 10, 2, '["2 Romana-Salate","100 g Parmesan","2 Scheiben Weißbrot für Croutons","2 Anchovisfilets","1 Knoblauchzehe","1 Eigelb","Zitronensaft, Olivenöl, Senf","Salz, Pfeffer"]'::jsonb, '["Brot in Würfel schneiden, in Öl mit Knoblauch goldbraun rösten.","Anchovis und Knoblauch fein hacken, mit Eigelb, Senf und Zitrone verrühren, Öl einrühren.","Salat waschen, trocken schleudern und in Stücke schneiden.","Salat mit Dressing mischen, Croutons und Parmesanflocken darauf geben."]'::jsonb, null),
  ('4', 'Tiramisu', 'Italienischer Klassiker mit Mascarpone, Espresso und Kakao.', 'Dessert', 30, 0, 6, '["500 g Mascarpone","4 Eier","80 g Zucker","200 ml starker Espresso (abgekühlt)","200 g Löffelbiskuits","Kakao zum Bestäuben","Optional: Amaretto"]'::jsonb, '["Eigelb mit Zucker schaumig schlagen, Mascarpone unterrühren.","Eiweiß steif schlagen und unter die Mascarpone-Masse heben.","Löffelbiskuits kurz in Espresso (evtl. mit Amaretto) tunken.","Schichtweise Biskuits und Creme in eine Form füllen, mit Kakao bestäuben.","Mindestens 4 Stunden kalt stellen."]'::jsonb, null),
  ('5', 'Haferflocken-Pfannkuchen', 'Sättigende Pfannkuchen mit Haferflocken – ideal zum Frühstück.', 'Frühstück', 10, 15, 2, '["100 g Haferflocken","1 Banane","2 Eier","50 ml Milch","1 TL Backpulver","Prise Zimt","Butter zum Braten","Ahornsirup oder Honig"]'::jsonb, '["Haferflocken grob mahlen, mit Banane, Eiern, Milch, Backpulver und Zimt mixen.","Butter in einer Pfanne erhitzen, Portionen Teig goldbraun backen.","Mit Ahornsirup oder Honig servieren."]'::jsonb, null),
  ('6', 'Hummus', 'Cremiger Kichererbsen-Dip mit Tahini, Zitrone und Knoblauch.', 'Snack', 15, 0, 4, '["400 g Kichererbsen (Dose, abgetropft)","2 EL Tahini","2 Knoblauchzehen","Saft von 1 Zitrone","3 EL Olivenöl","Kümmel, Salz, Pfeffer","Paprikapulver und Olivenöl zum Servieren"]'::jsonb, '["Kichererbsen mit Tahini, Knoblauch, Zitronensaft und Öl im Mixer pürieren.","Mit Kümmel, Salz und Pfeffer abschmecken.","Mit Paprikapulver und etwas Öl anrichten, mit Fladenbrot oder Gemüsesticks servieren."]'::jsonb, null)
on conflict (id) do nothing;
